DROP TABLE IF EXISTS TO_BRIDGE;
DROP TABLE IF EXISTS CC_BRIDGE;
DROP TABLE IF EXISTS BCC_BRIDGE;
DROP TABLE IF EXISTS BINARYFILES;
DROP TABLE IF EXISTS EMAILMESSAGE;
DROP TABLE IF EXISTS EMAIL;
DROP TABLE IF EXISTS EMAILADDRESS;
DROP TABLE IF EXISTS FOLDER;

CREATE TABLE FOLDER (
    FOLDER_ID int NOT NULL AUTO_INCREMENT,
    FOLDER_NAME varchar(50) NOT NULL UNIQUE,
    PRIMARY KEY(FOLDER_ID)
);

CREATE TABLE EMAIL (
    EMAIL_ID int NOT NULL AUTO_INCREMENT,
    EMAIL_FROM varchar(254) NOT NULL,
    EMAIL_SUBJECT varchar(255) NOT NULL default '',
    FOLDER_ID int NOT NULL default '0',
    SENT_DATE timestamp NULL,
    RECEIVED_DATE timestamp NULL,
    PRIMARY KEY(EMAIL_ID),
    FOREIGN KEY (FOLDER_ID) REFERENCES FOLDER(FOLDER_ID) ON DELETE CASCADE
);

CREATE TABLE BINARYFILES(
    FILE_ID int NOT NULL AUTO_INCREMENT,
    FILE_NAME varchar(255) NOT NULL default '',
    FILE_DATA mediumblob,
    EMAIL_ID int,
    CID varchar(255),
    PRIMARY KEY (FILE_ID),
    FOREIGN KEY (EMAIL_ID) REFERENCES EMAIL(EMAIL_ID) ON DELETE CASCADE
);

CREATE TABLE EMAILADDRESS(
    EA_ID int NOT NULL AUTO_INCREMENT,
    EA_NAME varchar(255) NOT NULL UNIQUE,
    PRIMARY KEY (EA_ID)
);

CREATE TABLE EMAILMESSAGE(
    MESSAGE_ID int NOT NULL AUTO_INCREMENT,
    CONTENT TEXT NOT NULL,
    ENCODING VARCHAR(50) NOT NULL DEFAULT "",
    MIME varchar(50) NOT NULL DEFAULT "",
    EMAIL_ID int,
    PRIMARY KEY (MESSAGE_ID),
    FOREIGN KEY (EMAIL_ID) REFERENCES EMAIL(EMAIL_ID) ON DELETE CASCADE
);

CREATE TABLE TO_BRIDGE(
    EA_ID int,
    EMAIL_ID int,
    PRIMARY KEY (EMAIL_ID, EA_ID),
    FOREIGN KEY (EA_ID) REFERENCES EMAILADDRESS(EA_ID),
    FOREIGN KEY (EMAIL_ID) REFERENCES EMAIL(EMAIL_ID) ON DELETE CASCADE
    
);

CREATE TABLE CC_BRIDGE(
    EA_ID int,
    EMAIL_ID int,
    PRIMARY KEY (EMAIL_ID, EA_ID),
    FOREIGN KEY (EA_ID) REFERENCES EMAILADDRESS(EA_ID),
    FOREIGN KEY (EMAIL_ID) REFERENCES EMAIL(EMAIL_ID) ON DELETE CASCADE
);

CREATE TABLE BCC_BRIDGE(
    EA_ID int,
    EMAIL_ID int,
    PRIMARY KEY (EMAIL_ID, EA_ID),
    FOREIGN KEY (EA_ID) REFERENCES EMAILADDRESS(EA_ID),
    FOREIGN KEY (EMAIL_ID) REFERENCES EMAIL(EMAIL_ID) ON DELETE CASCADE

);

INSERT INTO FOLDER (FOLDER_ID, FOLDER_NAME) VALUES (1, "Inbox");
INSERT INTO FOLDER (FOLDER_ID, FOLDER_NAME) VALUES(2, "Sent");
INSERT INTO FOLDER (FOLDER_ID, FOLDER_NAME) VALUES(3, "Spam");
INSERT INTO FOLDER (FOLDER_ID, FOLDER_NAME) VALUES (4, "Fun Stuff");


INSERT INTO EMAILADDRESS (EA_NAME) VALUES ("hipster@gmail.com");
INSERT INTO EMAILADDRESS (EA_NAME) VALUES ("superwalkurefan@gmail.com");
INSERT INTO EMAILADDRESS (EA_NAME) VALUES ("deltathaivun@gmail.com");
INSERT INTO EMAILADDRESS (EA_NAME) VALUES ("thaireceivecc1@gmail.com");

